package dev.grimholt.server.vanilla;
import java.util.*;
public final class VanillaGameplaySystems {
 public enum Difficulty{PEACEFUL,EASY,NORMAL,HARD} public enum Dimension{OVERWORLD,NETHER,END}
 public static final class GameRules{
  private final Map<String,Boolean>b=new HashMap<>();private final Map<String,Integer>i=new HashMap<>();
  public GameRules(){for(String k:new String[]{"doDaylightCycle","doMobSpawning","doMobLoot","mobGriefing","naturalRegeneration","doFireTick","doWeatherCycle"})b.put(k,true);b.put("keepInventory",false);i.put("randomTickSpeed",3);i.put("spawnRadius",10);i.put("maxEntityCramming",24);i.put("playersSleepingPercentage",100);}
  public boolean getBoolean(String k){return b.getOrDefault(k,false);}public int getInt(String k){return i.getOrDefault(k,0);}public void setBoolean(String k,boolean v){b.put(k,v);}public void setInt(String k,int v){if(v<0)throw new IllegalArgumentException();i.put(k,v);}public Map<String,Boolean> booleans(){return Map.copyOf(b);}public Map<String,Integer> integers(){return Map.copyOf(i);}
 }
 public static final class Attributes{private final Map<String,VanillaAttribute>v=new HashMap<>();public Attributes(){reg(new VanillaAttribute("minecraft:generic.max_health",20,1,1024));reg(new VanillaAttribute("minecraft:generic.movement_speed",.1,0,1024));reg(new VanillaAttribute("minecraft:generic.attack_damage",1,0,2048));reg(new VanillaAttribute("minecraft:generic.attack_speed",4,0,1024));reg(new VanillaAttribute("minecraft:generic.armor",0,0,30));reg(new VanillaAttribute("minecraft:generic.armor_toughness",0,0,20));reg(new VanillaAttribute("minecraft:generic.knockback_resistance",0,0,1));reg(new VanillaAttribute("minecraft:generic.luck",0,-1024,1024));}public void reg(VanillaAttribute a){v.put(a.id(),a);}public VanillaAttribute get(String id){return v.get(id);}public Map<String,VanillaAttribute>snapshot(){return Map.copyOf(v);}}
 public static final class Effects{private final Map<UUID,Map<String,VanillaEffect>>a=new HashMap<>();public void apply(UUID e,String id,int amp,int duration){if(amp<0||duration<=0)throw new IllegalArgumentException();a.computeIfAbsent(e,k->new HashMap<>()).put(id,new VanillaEffect(id,amp,duration));}public boolean has(UUID e,String id){return a.getOrDefault(e,Map.of()).containsKey(id);}public void tick(){for(var it=a.entrySet().iterator();it.hasNext();){var m=it.next().getValue();m.replaceAll((k,v)->new VanillaEffect(v.id(),v.amplifier(),v.durationTicks()-1));m.values().removeIf(v->v.durationTicks()<=0);if(m.isEmpty())it.remove();}}public Map<String,VanillaEffect>snapshot(UUID e){return Map.copyOf(a.getOrDefault(e,Map.of()));}}
 public static final class Stats{private final Map<UUID,Map<String,Long>>m=new HashMap<>();public void add(UUID p,String s,long n){if(n<0)throw new IllegalArgumentException();m.computeIfAbsent(p,k->new HashMap<>()).merge(s,n,Long::sum);}public long get(UUID p,String s){return m.getOrDefault(p,Map.of()).getOrDefault(s,0L);}}
 public static final class Advancements{private final Map<UUID,Set<String>>m=new HashMap<>();public void grant(UUID p,String id){m.computeIfAbsent(p,k->new HashSet<>()).add(id);}public void revoke(UUID p,String id){m.getOrDefault(p,Set.of()).remove(id);}public boolean has(UUID p,String id){return m.getOrDefault(p,Set.of()).contains(id);}}
 public static final class Permissions{private final Map<UUID,Set<String>>m=new HashMap<>();public void grant(UUID p,String s){m.computeIfAbsent(p,k->new HashSet<>()).add(s);}public void revoke(UUID p,String s){m.getOrDefault(p,Set.of()).remove(s);}public boolean has(UUID p,String s){return m.getOrDefault(p,Set.of()).contains(s)||m.getOrDefault(p,Set.of()).contains("*");}}
 public record DimensionRule(Dimension dimension,int minY,int maxY,float coordinateScale,boolean beds,boolean anchors,boolean skylight){}
 public static DimensionRule dimension(Dimension d){return switch(d){case OVERWORLD->new DimensionRule(d,-64,320,1,false,false,true);case NETHER->new DimensionRule(d,0,256,8,true,true,false);case END->new DimensionRule(d,0,256,1,false,false,true);};}
 private VanillaGameplaySystems(){}
}