package dev.grimholt.server.network;

import dev.grimholt.server.vanilla.*;
import java.io.*;
import java.util.*;

/**
 * Owns the 26.4-snapshot-3 configuration bootstrap. It deliberately consumes Grimholt's
 * generated reports rather than importing another server's packet classes.
 */
public final class VanillaConfigurationSync {
    // Preserve the protocol registry sequence used by the vanilla configuration
    // pipeline (also followed by Minestom 26_3). Registry payloads are stateful
    // protocol data, so sorting registry *names* here is not a valid substitute.
    private static final List<String> SYNCHRONIZED_REGISTRIES = List.of(
            "minecraft:chat_type",
            "minecraft:worldgen/biome",
            "minecraft:dialog",
            "minecraft:damage_type",
            "minecraft:trim_material",
            "minecraft:trim_pattern",
            "minecraft:banner_pattern",
            "minecraft:enchantment",
            "minecraft:painting_variant",
            "minecraft:jukebox_song",
            "minecraft:instrument",
            "minecraft:wolf_variant",
            "minecraft:wolf_sound_variant",
            "minecraft:cat_variant",
            "minecraft:cat_sound_variant",
            "minecraft:chicken_variant",
            "minecraft:chicken_sound_variant",
            "minecraft:cow_variant",
            "minecraft:cow_sound_variant",
            "minecraft:frog_variant",
            "minecraft:pig_variant",
            "minecraft:pig_sound_variant",
            "minecraft:zombie_nautilus_variant",
            "minecraft:world_clock",
            "minecraft:timeline",
            "minecraft:dimension_type",
            "minecraft:sulfur_cube_archetype",
            "minecraft:test_environment",
            "minecraft:test_instance"
    );

    private final VanillaGeneratedData generated;

    public VanillaConfigurationSync(VanillaGeneratedData generated) {
        this.generated = Objects.requireNonNull(generated, "generated");
    }

    /** Clientbound Select Known Packs. */
    public byte[] selectKnownPacks() {
        try {
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            VanillaProtocol26_2.writeVarInt(out, 1);
            VanillaProtocolCodec.writeString(out, "minecraft", 32767);
            VanillaProtocolCodec.writeString(out, "core", 32767);
            VanillaProtocolCodec.writeString(out, VanillaSnapshot.VERSION, 32767);
            return out.toByteArray();
        } catch (IOException e) {
            throw new UncheckedIOException(e);
        }
    }

    /**
     * Reads the serverbound Select Known Packs payload. The exact client list is
     * intentionally retained only as a compatibility observation; registry
     * ordering remains server authoritative.
     */
    public Set<String> readKnownPacks(byte[] payload) throws IOException {
        ByteArrayInputStream in = new ByteArrayInputStream(payload);
        int count = VanillaProtocol26_2.readVarInt(in);
        if (count < 0 || count > 64) throw new IOException("Invalid known-pack count: " + count);
        Set<String> result = new LinkedHashSet<>();
        for (int i = 0; i < count; i++) {
            String namespace = VanillaProtocolCodec.readString(in, 32767);
            String id = VanillaProtocolCodec.readString(in, 32767);
            String version = VanillaProtocolCodec.readString(in, 32767);
            result.add(namespace + ":" + id + "@" + version);
        }
        if (in.available() != 0) throw new IOException("Trailing data in known-packs packet");
        return Set.copyOf(result);
    }

    /**
     * Builds Update Tags payloads directly from the tag files generated by Mojang's
     * 26.4 data generator. Nested #tag references are expanded before encoding.
     */
    public List<byte[]> updateTagsPackets() {
        Optional<String> index = generated.read("reports/tag_files.json");
        if (index.isEmpty()) return List.of();
        Map<String, Map<String, List<String>>> byRegistry = new LinkedHashMap<>();
        for (Object value : VanillaJson.array(VanillaJson.parse(index.get()))) {
            if (!(value instanceof String path)) continue;
            String registry = tagRegistryForPath(path);
            if (registry == null) continue;
            String json = generated.read(path).orElse(null);
            if (json == null) continue;
            Map<String,Object> tag = VanillaJson.object(VanillaJson.parse(json));
            Object values = tag.get("values");
            if (!(values instanceof List<?> list)) continue;
            String tagId = "minecraft:" + path.substring(path.indexOf("/tags/") + 6)
                    .replaceFirst("^" + registryPath(registry) + "/", "")
                    .replaceAll("\\.json$", "");
            List<String> ids = new ArrayList<>();
            for (Object entry : list) {
                if (entry instanceof String s) ids.add(s);
                else if (entry instanceof Map<?,?> map && map.get("id") instanceof String s) ids.add(s);
            }
            byRegistry.computeIfAbsent(registry, ignored -> new LinkedHashMap<>()).put(tagId, ids);
        }

        if (byRegistry.isEmpty()) return List.of();

        // Snapshot 3 has one Update Tags packet containing a map of registries.
        // Parse the generated registry report once; it is shared by every tag group.
        Map<String,Object> registryReport = VanillaJson.object(
                VanillaJson.parse(generated.require("reports/registries.json")));
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try {
            VanillaProtocol26_2.writeVarInt(out, byRegistry.size());
            for (var registryEntry : byRegistry.entrySet()) {
                String registry = registryEntry.getKey();
                Map<String,Integer> ids = registryIds(registry, registryReport);
                Map<String,List<String>> tags = registryEntry.getValue();
                Map<String,List<String>> expanded = new LinkedHashMap<>();
                Map<String,List<String>> resolvedCache = new HashMap<>();
                for (String tagId : tags.keySet()) {
                    expanded.put(tagId, resolveTag(tagId, tags, new LinkedHashSet<>(), resolvedCache));
                }

                VanillaProtocolCodec.writeIdentifier(out, registry);
                VanillaProtocol26_2.writeVarInt(out, expanded.size());
                for (var tag : expanded.entrySet()) {
                    VanillaProtocolCodec.writeIdentifier(out, tag.getKey());
                    LinkedHashSet<Integer> resolved = new LinkedHashSet<>();
                    for (String id : tag.getValue()) {
                        Integer numeric = ids.get(id);
                        if (numeric != null) resolved.add(numeric);
                    }
                    VanillaProtocol26_2.writeVarInt(out, resolved.size());
                    for (int id : resolved) VanillaProtocol26_2.writeVarInt(out, id);
                }
            }
        } catch (IOException e) {
            throw new UncheckedIOException("Cannot encode 26.4 Update Tags", e);
        }
        return List.of(out.toByteArray());
    }

    private static List<String> resolveTag(String tagId,
                                            Map<String,List<String>> tags,
                                            Set<String> visiting,
                                            Map<String,List<String>> cache) {
        List<String> cached = cache.get(tagId);
        if (cached != null) return cached;
        if (!visiting.add(tagId)) {
            throw new IllegalStateException("Cyclic vanilla tag reference: " + visiting + " -> " + tagId);
        }
        LinkedHashSet<String> result = new LinkedHashSet<>();
        for (String value : tags.getOrDefault(tagId, List.of())) {
            if (value.startsWith("#")) {
                String nested = value.substring(1);
                if (!nested.contains(":")) nested = "minecraft:" + nested;
                result.addAll(resolveTag(nested, tags, visiting, cache));
            } else {
                result.add(value);
            }
        }
        visiting.remove(tagId);
        List<String> resolved = List.copyOf(result);
        cache.put(tagId, resolved);
        return resolved;
    }

    private Map<String,Integer> registryIds(String registry, Map<String,Object> root) {
        Object raw = root.get(registry);
        if (!(raw instanceof Map<?,?> map) || !(map.get("entries") instanceof Map<?,?> entries)) return Map.of();
        Map<String,Integer> ids = new HashMap<>();
        for (var entry : entries.entrySet()) {
            if (!(entry.getKey() instanceof String key) || !(entry.getValue() instanceof Map<?,?> value)) continue;
            if (value.get("protocol_id") instanceof Number n) ids.put(key, n.intValue());
        }
        return ids;
    }

    private static String tagRegistryForPath(String path) {
        int marker = path.indexOf("/tags/");
        if (marker < 0) return null;
        String rest = path.substring(marker + 6);
        int slash = rest.indexOf('/');
        if (slash < 0) return null;
        return switch (rest.substring(0, slash)) {
            // Mojang's data-pack directories use singular registry names.
            case "block", "blocks" -> "minecraft:block";
            case "item", "items" -> "minecraft:item";
            case "fluid", "fluids" -> "minecraft:fluid";
            case "entity_type", "entity_types" -> "minecraft:entity_type";
            case "game_event", "game_events" -> "minecraft:game_event";
            default -> null;
        };
    }

    private static String registryPath(String registry) {
        return switch (registry) {
            case "minecraft:block" -> "block";
            case "minecraft:item" -> "item";
            case "minecraft:fluid" -> "fluid";
            case "minecraft:entity_type" -> "entity_type";
            case "minecraft:game_event" -> "game_event";
            default -> "";
        };
    }

    /**
     * Registry entry payloads may omit their vanilla NBT only when the client
     * explicitly confirms the exact core pack advertised by this server.
     */
    public void requireCompatibleKnownPacks(Set<String> knownPacks) throws IOException {
        Objects.requireNonNull(knownPacks, "knownPacks");
        String expected = "minecraft:core@" + VanillaSnapshot.VERSION;
        if (!knownPacks.contains(expected)) {
            throw new IOException("Client did not acknowledge required vanilla pack " + expected
                    + "; refusing to send registry entries without their canonical NBT values. "
                    + "Client acknowledged: " + knownPacks);
        }
    }

    /**
     * Builds Registry Data payloads. For vanilla's core known pack the client
     * already owns the canonical entry values, so the Grimholt wire contract
     * may send entries with the optional NBT bit cleared. This keeps the
     * bootstrap deterministic while leaving custom-data overrides for the
     * future data-pack layer.
     */
    public List<byte[]> registryDataPackets() {
        // Dynamic registry values live in data-pack resources. reports/registries.json
        // describes registry types, so use the generated resource index instead.
        generated.requireAvailable();
        Map<String,Object> root = VanillaJson.object(
                VanillaJson.parse(generated.require("reports/registry_entries.json")));
        List<byte[]> packets = new ArrayList<>();
        List<String> missing = new ArrayList<>();

        for (String registryId : SYNCHRONIZED_REGISTRIES) {
            Object raw = root.get(registryId);
            if (!(raw instanceof List<?> entries)) {
                missing.add(registryId + " (registry absent from generated data-pack index)");
                continue;
            }
            List<String> names = entries.stream()
                    .filter(String.class::isInstance)
                    .map(String.class::cast)
                    .sorted()
                    .toList();
            try {
                ByteArrayOutputStream out = new ByteArrayOutputStream();
                VanillaProtocolCodec.writeIdentifier(out, registryId);
                VanillaProtocol26_2.writeVarInt(out, names.size());
                for (String name : names) {
                    VanillaProtocolCodec.writeIdentifier(out, name);
                    // The exact minecraft:core pack was negotiated before this method
                    // is called, so the client can reuse the canonical registry element.
                    VanillaProtocolCodec.writeBoolean(out, false);
                }
                packets.add(out.toByteArray());
            } catch (IOException e) {
                throw new UncheckedIOException("Cannot encode registry " + registryId, e);
            }
        }

        if (!missing.isEmpty() || packets.size() < 10) {
            throw new IllegalStateException(
                    "Incomplete Minecraft 26.4 registry-data index; packets=" + packets.size()
                    + ", missing=" + String.join(", ", missing)
                    + ". Verify reports/registry_entries.json against the pinned Snapshot 3 data.");
        }
        return List.copyOf(packets);
    }
}
