package dev.grimholt.server.api;
import dev.grimholt.api.*; import java.time.Duration; import java.util.concurrent.*; import java.util.concurrent.atomic.AtomicBoolean;
public final class BoundedScheduler implements Scheduler,AutoCloseable { private final ScheduledThreadPoolExecutor timer; private final ThreadPoolExecutor async; private final Semaphore admission; public BoundedScheduler(int workers,int maxQueued){if(workers<1||maxQueued<1)throw new IllegalArgumentException();admission=new Semaphore(maxQueued);timer=new ScheduledThreadPoolExecutor(1,r->new Thread(r,"Grimholt-Scheduler"));timer.setRemoveOnCancelPolicy(true);async=new ThreadPoolExecutor(workers,workers,30,TimeUnit.SECONDS,new ArrayBlockingQueue<>(maxQueued),r->new Thread(r,"Grimholt-Async"),new ThreadPoolExecutor.AbortPolicy());}
 private void acquire(){if(!admission.tryAcquire())throw new RejectedExecutionException("Grimholt scheduler queue is full");}
 public Task run(Runnable task){acquire();var c=new AtomicBoolean();try{timer.execute(()->{try{if(!c.get())task.run();}finally{admission.release();}});return new H(c,null,false,true);}catch(RuntimeException e){admission.release();throw e;}}
 public Task runAsync(Runnable task){acquire();var c=new AtomicBoolean();try{async.execute(()->{try{if(!c.get())task.run();}finally{admission.release();}});return new H(c,null,false,true);}catch(RuntimeException e){admission.release();throw e;}}
 public Task runLater(Duration d,Runnable task){if(d.isNegative())throw new IllegalArgumentException("delay < 0");acquire();var c=new AtomicBoolean();try{var f=timer.schedule(()->{try{if(!c.get())task.run();}finally{admission.release();}},d.toNanos(),TimeUnit.NANOSECONDS);return new H(c,f,false,false);}catch(RuntimeException e){admission.release();throw e;}}
 public Task runRepeating(Duration initial,Duration period,Runnable task){if(initial.isNegative()||period.isZero()||period.isNegative())throw new IllegalArgumentException();acquire();var c=new AtomicBoolean();try{var f=timer.scheduleAtFixedRate(()->{if(!c.get())try{task.run();}catch(Throwable ignored){}},initial.toNanos(),period.toNanos(),TimeUnit.NANOSECONDS);return new H(c,f,true,false);}catch(RuntimeException e){admission.release();throw e;}}
 public void close(){timer.shutdownNow();async.shutdownNow();}
 private final class H implements Task {final AtomicBoolean c;final Future<?> f;final boolean repeat;final boolean oneShot;H(AtomicBoolean c,Future<?>f,boolean r,boolean o){this.c=c;this.f=f;repeat=r;oneShot=o;}public boolean cancel(){if(!c.compareAndSet(false,true))return false;if(f!=null)f.cancel(false);if(repeat||oneShot)admission.release();return true;}public boolean cancelled(){return c.get();}}
}
